#!/bin/bash
openssl speed -evp aes-128-ctr

#openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
#openssl rsa -pubout -in private_key.pem -out public_key.pem
#openssl dgst -sha256 -sign private.pem -out signature.bin teste.txt
#openssl dgst -sha256 -verify public.pem -signature signature.bin teste.txt